site_name: PnP/PnPjs

docs_dir: 'docs'

nav:
  - Home: 'index.md'
  - 'Getting Started': 'getting-started.md'
  - 'V2->V3 Transition': 'transition-guide.md'
  - 'Year in Review':
    - '2022': 'news/2022-year-in-review.md'
    - '2021': 'news/2021-year-in-review.md'
    - '2020': 'news/2020-year-in-review.md'
  - 'Library Usage Tips':
    - 'Authentication': 'concepts/authentication.md'
    - 'In SPFx': 'concepts/auth-spfx.md'
    - 'In Browser': 'concepts/auth-browser.md'
    - 'In NodeJS': 'concepts/auth-nodejs.md'
    - 'Batching': 'concepts/batching.md'
    - 'Batching & Caching': 'concepts/batching-caching.md'
    - 'Calling Other Endpoints': 'concepts/calling-other-endpoints'
    - 'Custom Bundling': 'concepts/custom-bundle.md'
    - 'Error-Handling': 'concepts/error-handling.md'
    - 'Project Config/Services Setup': 'concepts/project-preset.md'
    - 'Selective Imports': 'concepts/selective-imports.md'
    - 'Typings': 'concepts/typings.md'
    - 'Using Behaviors': 'core/behaviors.md'
    - 'Nightly Builds': 'concepts/nightly-builds.md'
  - Packages:
    - Packages: 'packages.md'
    - azidjsclient:
      - azidjsclient: 'azidjsclient/index.md'
    - core:
      - core: 'packages/#core'
      - behaviors: 'core/behaviors.md'
      - observers: 'core/observers.md'
      - moments: 'core/moments.md'
      - timeline: 'core/timeline.md'
      - storage: 'core/storage.md'
      - util: 'core/util.md'
    - graph: 
      - graph: 'packages/#graph'
      - behaviors: 'graph/behaviors.md'
      - bookings: 'graph/bookings.md'
      - columns: 'graph/columns.md'
      - 'content types': 'graph/content-types.md'
      - groups: 'graph/groups.md'
      - insights: 'graph/insights.md'
      - contacts: 'graph/contacts.md'
      - 'cloud communications': 'graph/cloud-communications.md'
      - calendars: 'graph/calendars.md'
      - 'directory objects': 'graph/directoryobjects.md'
      - invitations: 'graph/invitations.md'
      - items: 'graph/items.md'
      - lists: 'graph/lists.md'
      - messages: 'graph/messages.md'
      - onedrive: 'graph/onedrive.md'
      - outlook: 'graph/outlook.md'
      - photos: 'graph/photos.md'
      - planner: 'graph/planner.md'
      - search: 'graph/search.md'
      - shares: 'graph/shares.md'
      - sites: 'graph/sites.md'
      - subscriptions: 'graph/subscriptions.md'
      - teams: 'graph/teams.md'
      - users: 'graph/users.md'
    - logging: 
      - logging: 'logging/index.md'
    - msaljsclient:
      - msaljsclient: 'msaljsclient/index.md'
    - nodejs:
      - nodejs: 'packages/#nodejs'
      - behaviors: 'nodejs/behaviors.md'
      - 'sp Extensions': 'nodejs/sp-extensions.md'
    - queryable:
      - queryable: 'packages/#queryable'
      - behaviors: 'queryable/behaviors.md'
      - extensions: 'queryable/extensions.md'
      - queryable: 'queryable/queryable.md'
    - sp:
      - sp: 'packages/#sp'
      - behaviors: 'sp/behaviors.md'
      - 'alias parameters': 'sp/alias-parameters.md'
      - 'ALM api': 'sp/alm.md'
      - attachments: 'sp/attachments.md'
      - 'client-side pages': 'sp/clientside-pages.md'
      - 'column defaults': 'sp/column-defaults.md'
      - 'comments and likes': 'sp/comments-likes.md'
      - 'content types': 'sp/content-types.md'
      - 'context info': 'sp/context-info.md'
      - Favorites: 'sp/favorites.md'
      - Features: 'sp/features.md'
      - Fields: 'sp/fields.md'
      - Files: 'sp/files.md'
      - Folders: 'sp/folders.md'
      - Forms: 'sp/forms.md'
      - GroupSiteManager: 'sp/groupSiteManager.md'
      - Hubsites: 'sp/hubsites.md'
      - 'List Items': 'sp/items.md'
      - Lists: 'sp/lists.md'      
      - 'Navigation': 'sp/navigation.md'
      - Permissions: 'sp/permissions.md'
      - Profiles: 'sp/profiles.md'
      - 'Recycle Bin': 'sp/recycle-bin.md'
      - 'Regional Settings': 'sp/regional-settings.md'
      - 'Related Items': 'sp/related-items.md'
      - Search: 'sp/search.md'
      - Security: 'sp/security.md'
      - Sharing: 'sp/sharing.md'
      - 'Site Designs': 'sp/site-designs.md'
      - 'Site Groups': 'sp/site-groups.md'
      - 'Site Scripts': 'sp/site-scripts.md'
      - 'Site Users': 'sp/site-users.md'
      - Sites: 'sp/sites.md'
      - Social: 'sp/social.md'
      - 'SP.Publishing.SitePageService': 'sp/publishing-sitepageservice.md'
      - 'SP.Utilities.Utility': 'sp/sp-utilities-utility.md'
      - Subscriptions: 'sp/subscriptions.md'
      - Taxonomy: 'sp/taxonomy.md'
      - 'Tenant Properties': 'sp/tenant-properties.md'
      - 'User custom actions': 'sp/user-custom-actions.md'      
      - Views: 'sp/views.md'
      - Webs: 'sp/webs.md'
    - sp-admin:
      - sp-admin: 'sp-admin/index.md'
  - Advanced:
    - 'Custom Bundle': 'concepts/custom-bundle.md'
    - 'Custom Call/Path': 'concepts/invokable.md'
    - 'Behaviors': 'core/behaviors.md'
    - 'Behavior Recipes': 'core/behavior-recipes.md'
    - 'Timeline/Moments': 'core/timeline.md'
    - 'Client-Side Pages': 'concepts/adv-clientside-pages.md'
  - Contributing:
    - 'Contributing': 'contributing/index.md'
    - 'Set Up Dev Machine': 'contributing/setup-dev-machine.md'
    - 'Settings': 'contributing/settings.md'
    - 'Understanding Library Internals': 'core/timeline.md'
    - 'Expanding the Library': 'contributing/extending-the-library.md'
    - 'Npm Scripts': 'contributing/npm-scripts.md'
    - 'Local Debug Config': 'contributing/local-debug-configuration.md'
    - 'Debugging': 'contributing/debugging.md'
    - 'Tests': 'contributing/debug-tests.md'
    - 'Documentation': 'contributing/documentation.md'
    - 'Pull Requests': 'contributing/pull-requests.md'
  - Legacy Docs:
    - V1: 'v1/index.html'
    - V2: 'v2/index.html'

theme:
  name: 'material'
  custom_dir: 'docs/_theme'
  palette:
    primary: 'blue'
  logo: 'img/Logo.png'
  feature:
    tabs: true

extra_css:
  - 'css/extra.css'

markdown_extensions:
  - admonition
  - toc:
      permalink: true

plugins:
  - search
  - markdownextradata
  - redirects:
      redirect_maps:
          'getting-started-dev.md': 'contributing/index.md'
          'debugging.md': 'contributing/debugging.md'
          'debug-tests.md': 'contributing/debug-tests.md'
          'documentation.md': 'contributing/documentation.md'

extra:
  social:
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/m365pnpjs'
    - icon: 'fontawesome/brands/youtube'
      link: 'http://aka.ms/community/videos'
    - icon: 'fontawesome/brands/microsoft'
      link: 'https://aka.ms/community/home'

repo_url: https://github.com/pnp/pnpjs

edit_uri: tree/version-3/docs

site_url: https://pnp.github.io/pnpjs/