name: v3 Nightly Builds

on:
  schedule:
  - cron: "0 2 * * 1-5"

  workflow_dispatch:

jobs:
  publish-v3-nightly:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: version-3    
      # setup nodejs
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
          cache-dependency-path: package-lock.json
          
      # Run the npm install          
      - run: npm ci

      # Runs a set of commands using the runners shell
      - name: Test - not setup
        run: echo this would be the tests

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: npm run pnp-publish-v3nightly
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
